### ISSUE TITLE
Diamond-square algorithm producing incorrect results on web

### ISSUE THREAD

**Issue by anissen** [whuop/hxNoise#1]
The diamond-square sample takes a very long time (around 10 seconds) and then produces (something like) this on web (Chrome, OS X):
![](https://files.gitter.im/snowkit/public/PkTt/Screen-Shot-2016-04-01-at-10.26.24.png)

Running the same sample but using simply `Math.random` as the random function produces this interesting result:
![screen shot 2016-04-09 at 21 58 17](https://cloud.githubusercontent.com/assets/879967/14406055/4339eee2-fe9e-11e5-9817-27d297999c62.png)

Running the diamond-square sample on OS X natively produces this result:
![screen shot 2016-04-09 at 21 56 42](https://cloud.githubusercontent.com/assets/879967/14406059/54391a10-fe9e-11e5-81ef-b283448a01f4.png)

Maybe some variables are uninitialized causing these platform differences?

**Comment by whuop** [comment]
Weird stuff! Will look into it very shortly. It definitely shouldn't do that on web.
